# This workflow will run rush update and add the result to the pull request
name: Rush update
# Trigger the workflow on pull request events
on: [pull_request]
jobs:
  rush-update:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-18.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.50.0

     #- name: Rush Install
     #  uses: advancedcsg-open/actions-rush@v1.4.5

      - name: Rush Build
        run: rush build
