# This workflow will run rush update and add the result to the pull request
name: Rush update
# Trigger the workflow on labels added or removed for PRs
on:
  pull_request_target:
    types:
      - labeled
jobs:
  rush-update:
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-18.04
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Rush CLI
        run: npm install -g @microsoft/rush@5.57.1

      - name: Install sync script dependencies
        run: cd tools && npm install

      - name: Run sync script
        run: node tools/sync.js

      - name: Rush Update
        run: rush update --purge

      - name: Rush Check
        run: rush check

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          author_name: tk-elbot
          author_email: engineering@travelperk.com
          message: 'Rush sync & update'
